### ISSUE TITLE
To-do list for 3craft

### ISSUE THREAD

**Issue by popdynamite5511** [popdynamite5511/3craft#1]
Here's some things I want to properly implement before releasing the first version of the game. I'll check them off as they are completed.

- [ ] Proper terrain generation
- [x] More blocks, hopefully implementing at least the most basic blocks
- [ ] Render a hand when no blocks are being held, also allow players to hold nothing
- [ ] Simple structure generation (trees, water and lava lakes?)
- [x] Background music

Of course I will try to add more than this. I'll update this if I think of more stuff.
If you want to contribute, make a pull request and I'll have a look

**Comment by popdynamite5511** [comment]
Hand is partially complete, although glitched
